server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sbp
    username: sbpadmin
    password: Te8XxeaGq34Z43M
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
jwt:
  secret:
    key: FI8x0wlNkRXsqKA1fVfV0VLI0gaEMCoN
oauth2:
  google:
    client-id: 발급받은client-id입력
    client-secret: 발급받은client-secret입력
    redirect-uri: http://localhost:8081/auth/google
    authorization-server-uri: https://oauth2.googleapis.com/token
    resource-server-uri: https://www.googleapis.com/oauth2/v2/userinfo
external-api:
  typicode:
    url: https://jsonplaceholder.typicode.com
    todo-path: /todos

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sbp
    username: sbpadmin
    password: Te8XxeaGq34Z43M
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
jwt:
  secret:
    key: FI8x0wlNkRXsqKA1fVfV0VLI0gaEMCoN
oauth2:
  google:
    client-id: 발급받은client-id입력
    client-secret: 발급받은client-secret입력
    redirect-uri: http://localhost:8081/auth/google
    authorization-server-uri: https://oauth2.googleapis.com/token
    resource-server-uri: https://www.googleapis.com/oauth2/v2/userinfo
external-api:
  typicode:
    url: https://jsonplaceholder.typicode.com
    todo-path: /todos